### ISSUE TITLE
Resource limit reflected only in kube-events container but not in forwarder container.

### ISSUE THREAD

**Issue by Yiyito11** [newrelic/nri-kube-events#186]
^^ Provide a general summary of the issue in the title above. ^^ 

## Description
I have set in values.yaml resources in the nri-bundle for kube-events but resources are not in forwarder container. They are only in kube-events container.
## Expected Behavior
I need that resources also are present in the forwarder container (we have some internal policies in k8s that if a container doesn´t have resource limits it won´t start)

## Steps to Reproduce
1° created new values.yaml to override values for the nri-bundle.
Added resource block under nri-kube-events.

```
global:
    licenseKey: Mykey
    cluster: mycluster

newrelic-prometheus-agent:
  # Automatically scrape prometheus metrics for annotated services in the cluster
  # Collecting prometheus metrics for large clusters might impact data usage significantly
  enabled: false
nri-metadata-injection:
  # Deploy our webhook to link APM and Kubernetes entities
  enabled: false
nri-kube-events:
  # Report Kubernetes events
  enabled: true

  resources:  
    limits:
      cpu: 300m
      # This value is being used as a source for default memory_limiter processor configurations
      memory: 500Mi

newrelic-logging:
  # Report logs for containers running in the cluster
  enabled: false
kube-state-metrics:
  # Deploy kube-state-metrics in the cluster.
  # Set this to true unless it is already deployed.
  enabled: true

  resources:
    limits:
      cpu: 300m
      # This value is being used as a source for default memory_limiter processor configurations
      memory: 500Mi

newrelic-infrastructure:
  enabled: true

  kubelet:
    resources:
      limits:
        cpu: 300m
        # This value is being used as a source for default memory_limiter processor configurations
        memory: 500Mi
  
  ksm:
    resources:
      limits:
        cpu: 300m
        # This value is being used as a source for default memory_limiter processor configurations
        memory: 500Mi
    
    containerSecurityContext: 
    capabilities:
      drop:
        - NET_RAW
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 20000
    runAsGroup: 20000
    allowPrivilegeEscalation: false

```
2° executed a dry-run to check deployment.yaml
`helm upgrade --install newrelic-k8s nri-bundle\ -f .\nri-bundle\values-newrelic.yaml --dry-run -n monitoringapps | Out-File result6.yaml
`
As you can see resources not being under forwarder container
![image](https://user-images.githubusercontent.com/23485888/222244369-e338efd9-9601-4394-9505-b9ec36787b8a.png)

## Your Environment

Latest New-Relic Helm chart

## Additional context
Add any other context about the problem here. For example, relevant community posts or support tickets.

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*
